version: 2.1
jobs:
  deploy_prd:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          command: |
            pip3 install jinja2
            cd src
            python3 render.py
      - run:
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gsutil cp -r ./src/rendered gs://hacoviva.jp

  deploy_dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          command: |
            pip3 install jinja2
            cd src
            python3 render.py
      - run:
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            ls
            ls ./src
            ls ./src/rendered
            gsutil cp -r ./src/rendered gs://dev.hacoviva.jp


workflows:
  version: 2
  deploy_prd:
    jobs:
      - deploy_prd:
          filters:
            branches:
              only: master

      - deploy_dev:
          filters:
            branches:
              ignore: master
